services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    entrypoint: /docker-entrypoint-initdb.d/init-database.sh

  api:
    build: ./src
    container_name: node_api_container
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  db_data:
