services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: ./src
    container_name: node_api_container
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql_container
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_DATABASE=ecommerce_db
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
